# Generated by Django 3.1.2 on 2020-11-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('rollno', models.CharField(max_length=12, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('section', models.CharField(choices=[('C1', 'CSE-1'), ('C2', 'CSE-2'), ('C3', 'CSE-3'), ('E1', 'ECE-1'), ('E2', 'ECE-2'), ('E3', 'ECE-3'), ('J1', 'EEE-1'), ('J2', 'EEE-2'), ('I3', 'IT-3'), ('I1', 'IT-1'), ('I2', 'IT-2'), ('A1', 'MECH-1'), ('A2', 'MECH-2'), ('D1', 'CIVIL-1'), ('D2', 'CIVIL-2'), ('P', 'PROD'), ('K', 'CHEM'), ('B', 'BIOTECH'), ('L', 'MBA'), ('M', 'MTECH'), ('N', 'MCA')], max_length=2)),
                ('year', models.CharField(choices=[('1st', 'first year'), ('2nd', 'second year'), ('3rd', 'third year'), ('4th', 'fourth year')], max_length=3)),
                ('height_one', models.FloatField(default=1.0)),
                ('weight_one', models.FloatField(default=0.0)),
                ('height_two', models.FloatField(default=1.0)),
                ('weight_two', models.FloatField(default=0.0)),
                ('feedback', models.CharField(default='empty feedback', max_length=500)),
                ('fb_recorded', models.BooleanField(default=False)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')])),
                ('second', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')])),
                ('third', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')])),
                ('fourth', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')])),
                ('fifth', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')])),
                ('suggestion', models.CharField(default='', max_length=500)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
