# Generated by Django 3.1.2 on 2020-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='First',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fifth',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fourth',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='second',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='third',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], null=True),
        ),
    ]
