# Generated by Django 3.1.2 on 2020-11-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0003_auto_20201113_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='First',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fifth',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fourth',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='second',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='third',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisfactory'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=1),
        ),
    ]
