# Generated by Django 3.1.1 on 2020-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0005_auto_20201113_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rollno',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
