# Generated by Django 3.1.1 on 2020-11-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0006_auto_20201113_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rollno',
            field=models.IntegerField(unique=True),
        ),
    ]
