# Generated by Django 3.1.1 on 2020-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0007_auto_20201113_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rollno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
