# Generated by Django 3.1.1 on 2020-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0008_auto_20201113_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
