# Generated by Django 3.1.1 on 2020-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0009_auto_20201114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(verbose_name='last login'),
        ),
    ]
