# Generated by Django 3.1.1 on 2020-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0010_auto_20201121_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='last login'),
        ),
    ]
