# Generated by Django 3.1.1 on 2020-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsrs', '0011_auto_20201121_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(null=True, verbose_name='Previous Login'),
        ),
    ]
